name: Build and Push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Course Service
        uses: docker/build-push-action@v2
        with:
          context: ./course-service
          file: ./course-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/course-service:latest

      - name: Build and push Student Service
        uses: docker/build-push-action@v2
        with:
          context: ./student-service
          file: ./student-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/student-service:latest

      - name: Build and push Assessment Service
        uses: docker/build-push-action@v2
        with:
          context: ./assessment-service
          file: ./assessment-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/assessment-service:latest
